# Uncomment this line to define a global platform for your project
platform :ios, '9.0'

target 'PyfBackend' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
  pod 'Alamofire', '~> 2.0'
end
